jobs:
  uploadOne:
    name: upload release binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - id: make fake one
        name: make fake one
        run: "echo 'fake contents for one' >> one"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: get_release_url
        name: Get release url
        uses: "bruceadams/get-release@v1.2.2"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: upload release binary
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          asset_content_type: application/octet-stream
          asset_name: fake
          asset_path: fake
          upload_url: "${{ steps.get_release_url.outputs.upload_url }}"
  uploadTwo:
    name: upload release binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - id: make fake two
        name: make fake two
        run: "echo 'fake contents for two' >> two"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: get_release_url
        name: Get release url
        uses: "bruceadams/get-release@v1.2.2"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: upload release binary
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          asset_content_type: application/octet-stream
          asset_name: fake
          asset_path: fake
          upload_url: "${{ steps.get_release_url.outputs.upload_url }}"
name: Upload release binary
on:
  release:
    types:
      - created
